# prediction categories
PredictionCategory.find_or_create_by(name: "First Set Opener", set_number: 0, setlist_position: 0)
PredictionCategory.find_or_create_by(name: "First Set Closer", set_number: 0, setlist_position: -1)
PredictionCategory.find_or_create_by(name: "Second Set Opener", set_number: 1, setlist_position: 0)
PredictionCategory.find_or_create_by(name: "Second Set Closer", set_number: 1, setlist_position: -1)
PredictionCategory.find_or_create_by(name: "Encore", set_number: 2)



# Summer Tour 2020
# TODO: localize times

summer_2020 = ConcertTour.find_or_create_by(name: "Summer 2020")
Concert.find_or_create_by(
    show_time: DateTime.new(2020,7,14,19,30), venue_name: "Matthew Knight Arena, Eugene, OR", concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/eugene_or.jpg"), filename: 'eugene_or.jpg', content_type: "application/jpg")


Concert.find_or_create_by(
    show_time: DateTime.new(2020,7,15,19,30), venue_name: "Matthew Knight Arena, Eugene, OR", concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/eugene_or.jpg"), filename: 'eugene_or.jpg', content_type: "application/jpg")

Concert.find_or_create_by(
    show_time: DateTime.new(2020,7,17,19,30), venue_name: "Gorge Amphitheatre, George, WA", concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/george_wa.jpg"), filename: 'geore_wa.jpg', content_type: "application/jpg")
Concert.find_or_create_by(
    show_time: DateTime.new(2020,7,18,19,30), venue_name: "Gorge Amphitheatre, George, WA", concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/george_wa.jpg"), filename: 'geore_wa.jpg', content_type: "application/jpg")
Concert.find_or_create_by(
    show_time: DateTime.new(2020,7,19,19,30), venue_name: "Gorge Amphitheatre, George, WA", concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/george_wa.jpg"), filename: 'geore_wa.jpg', content_type: "application/jpg")
Concert.find_or_create_by(
    show_time: DateTime.new(2020,7,21,18,30),
    venue_name: "Lake Tahoe Outdoor Arena at Harveys, Stateline, NV",
    concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/stateline_nv.jpg"), filename: 'stateline_nv.jpg', content_type: "application/jpg")
Concert.find_or_create_by(
    show_time: DateTime.new(2020,7,22,18,30),
    venue_name: "Lake Tahoe Outdoor Arena at Harveys, Stateline, NV",
    concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/stateline_nv.jpg"), filename: 'stateline_nv.jpg', content_type: "application/jpg")
Concert.find_or_create_by(
    show_time: DateTime.new(2020,7,24,21,30), venue_name: "The Forum, Inglewood, CA", concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/inglewood_ca.jpeg"), filename: 'inglewood_ca.jpeg', content_type: "application/jpg")
Concert.find_or_create_by(
    show_time: DateTime.new(2020,7,25,21,30), venue_name: "Chase Center, San Francisco, CA", concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/san_fransisco_ca.jpg"), filename: 'san_fransisco_ca.jpg', content_type: "application/jpg")

Concert.find_or_create_by(
    show_time: DateTime.new(2020,7,26,21,30), venue_name: "Chase Center, San Francisco, CA", concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/san_fransisco_ca.jpg"), filename: 'san_fransisco_ca.jpg', content_type: "application/jpg")

Concert.find_or_create_by(
    show_time: DateTime.new(2020,7,29,21,00), venue_name: "Walmart AMP, Rogers, AR", concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/rogers_ar.jpg"), filename: 'rogers_ar.jpg', content_type: "application/jpg")

Concert.find_or_create_by(
    show_time: DateTime.new(2020,7,31,19,30), venue_name: "Oak Mountain Amphitheatre, Pelham, AL", concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/pelham_al.jpg"), filename: 'pelham_al.jpg', content_type: "application/jpg")
Concert.find_or_create_by(
    show_time: DateTime.new(2020,8,1,19,00), venue_name: "Piedmont Park, Atlanta, GA", concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/atlanta_ga.jpg"), filename: 'atlanta_ga.jpg', content_type: "application/jpg")
Concert.find_or_create_by(
    show_time: DateTime.new(2020,8,2,19,00), venue_name: "Piedmont Park, Atlanta, GA", concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/atlanta_ga.jpg"), filename: 'atlanta_ga.jpg', content_type: "application/jpg")
Concert.find_or_create_by(
    show_time: DateTime.new(2020,8,4,19,00), venue_name: "Ascend Amphitheater, Nashville, TN", concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/nashville_tn.jpg"), filename: 'nashville_tn.jpg', content_type: "application/jpg")
Concert.find_or_create_by(
    show_time: DateTime.new(2020,8,5,19,00), venue_name: "Ascend Amphitheater, Nashville, TN", concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/nashville_tn.jpg"), filename: 'nashville_tn.jpg', content_type: "application/jpg")
Concert.find_or_create_by(
    show_time: DateTime.new(2020,8,7,21,00), venue_name: "Ruoff Music Center, Noblesville, IN", concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/noblesville_in.jpg"), filename: 'noblesville_in.jpg', content_type: "application/jpg")
Concert.find_or_create_by(
    show_time: DateTime.new(2020,8,8,21,00), venue_name: "Ruoff Music Center, Noblesville, IN", concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/noblesville_in.jpg"), filename: 'noblesville_in.jpg', content_type: "application/jpg")
Concert.find_or_create_by(
    show_time: DateTime.new(2020,8,9,21,00), venue_name: "Ruoff Music Center, Noblesville, IN", concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/noblesville_in.jpg"), filename: 'noblesville_in.jpg', content_type: "application/jpg")
Concert.find_or_create_by(
    show_time: DateTime.new(2020,8,11,19,00), venue_name: "Giant Center, Hershey, PA", concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/hershey_pa.jpg"), filename: 'hershey_pa.jpg', content_type: "application/jpg")
Concert.find_or_create_by(
    show_time: DateTime.new(2020,8,12,19,00), venue_name: "Giant Center, Hershey, PA", concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/hershey_pa.jpg"), filename: 'hershey_pa.jpg', content_type: "application/jpg")
Concert.find_or_create_by(
    show_time: DateTime.new(2020,8,14,19,30), venue_name: "Atlantic City Beach, Atlantic City, NJ", concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/atlantic_city_nj.jpg"), filename: 'atlantic_city_nj.jpg', content_type: "application/jpg")
Concert.find_or_create_by(
    show_time: DateTime.new(2020,8,15,19,30), venue_name: "Atlantic City Beach, Atlantic City, NJ", concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/atlantic_city_nj.jpg"), filename: 'atlantic_city_nj.jpg', content_type: "application/jpg")
Concert.find_or_create_by(
    show_time: DateTime.new(2020,8,16,19,30), venue_name: "Atlantic City Beach, Atlantic City, NJ", concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/atlantic_city_nj.jpg"), filename: 'atlantic_city_nj.jpg', content_type: "application/jpg")
Concert.find_or_create_by(
    show_time: DateTime.new(2020,9,04,19,30), venue_name: "DICK’S Sporting Goods Park, Commerce City, CO", concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/commerce_city_co.jpg"), filename: 'commerce_city_co.jpg', content_type: "application/jpg")
Concert.find_or_create_by(
    show_time: DateTime.new(2020,9,05,19,30), venue_name: "DICK’S Sporting Goods Park, Commerce City, CO", concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/commerce_city_co.jpg"), filename: 'commerce_city_co.jpg', content_type: "application/jpg")
Concert.find_or_create_by(
    show_time: DateTime.new(2020,9,06,19,30), venue_name: "DICK’S Sporting Goods Park, Commerce City, CO", concert_tour: summer_2020
).venue_image.attach(io: File.open("#{Dir.home}/Desktop/venue_images/commerce_city_co.jpg"), filename: 'commerce_city_co.jpg', content_type: "application/jpg")



Song.find_or_create_by(name: "46 Days")
Song.find_or_create_by(name: "50 Ways to Leave Your Lover")
Song.find_or_create_by(name: "555")
Song.find_or_create_by(name: "0.21875")
Song.find_or_create_by(name: "99 Problems")
Song.find_or_create_by(name: "A Apolitical Blues")
Song.find_or_create_by(name: "A Day in the Life")
Song.find_or_create_by(name: "A Song I Heard the Ocean Sing")
Song.find_or_create_by(name: "AC/DC Bag")
Song.find_or_create_by(name: "Access Me")
Song.find_or_create_by(name: "Acoustic Army")
Song.find_or_create_by(name: "After Midnight")
Song.find_or_create_by(name: "Ain't Love Funny")
Song.find_or_create_by(name: "Alaska")
Song.find_or_create_by(name: "Albuquerque")
Song.find_or_create_by(name: "All Along the Watchtower")
Song.find_or_create_by(name: "All Blues")
Song.find_or_create_by(name: "All Down the Line")
Song.find_or_create_by(name: "All That You Dream")
Song.find_or_create_by(name: "All Things Reconsidered")
Song.find_or_create_by(name: "All of These Dreams")
Song.find_or_create_by(name: "All the Pain Through the Years")
Song.find_or_create_by(name: "Also Sprach Zarathustra")
Song.find_or_create_by(name: "Alumni Blues")
Song.find_or_create_by(name: "Alumni Blues Jam")
Song.find_or_create_by(name: "Amazing Grace")
Song.find_or_create_by(name: "Amazing Grace Jam")
Song.find_or_create_by(name: "Ambient Jam")
Song.find_or_create_by(name: "American Woman")
Song.find_or_create_by(name: "Amidst the Peals of Laughter")
Song.find_or_create_by(name: "Amoreena")
Song.find_or_create_by(name: "Anarchy")
Song.find_or_create_by(name: "Andy's Chest")
Song.find_or_create_by(name: "Any Colour You Like")
Song.find_or_create_by(name: "Anything But Me")
Song.find_or_create_by(name: "Arc")
Song.find_or_create_by(name: "Architect")
Song.find_or_create_by(name: "Army of One")
Song.find_or_create_by(name: "Art Jam")
Song.find_or_create_by(name: "Ass Handed")
Song.find_or_create_by(name: "Auld Lang Syne")
Song.find_or_create_by(name: "Autumn Leaves")
Song.find_or_create_by(name: "Avenu Malkenu")
Song.find_or_create_by(name: "Axilla")
Song.find_or_create_by(name: "Axilla (Part II)")
Song.find_or_create_by(name: "Baby Elephant Walk")
Song.find_or_create_by(name: "Baby Lemonade")
Song.find_or_create_by(name: "Babylon Baby")
Song.find_or_create_by(name: "Babylon is Burning")
Song.find_or_create_by(name: "Back Porch Boogie Blues")
Song.find_or_create_by(name: "Back at the Chicken Shack")
Song.find_or_create_by(name: "Back in the U.S.S.R.")
Song.find_or_create_by(name: "Back on the Train")
Song.find_or_create_by(name: "Backwards Down the Number Line")
Song.find_or_create_by(name: "Band/Crew Football Theme Song")
Song.find_or_create_by(name: "Bathtub Gin")
Song.find_or_create_by(name: "Beaumont Rag")
Song.find_or_create_by(name: "Beauty of My Dreams")
Song.find_or_create_by(name: "Beauty of a Broken Heart")
Song.find_or_create_by(name: "Been Caught Stealing")
Song.find_or_create_by(name: "Bell Boy")
Song.find_or_create_by(name: "Bertha")
Song.find_or_create_by(name: "Big Alligator")
Song.find_or_create_by(name: "Big Ball Jam")
Song.find_or_create_by(name: "Big Balls")
Song.find_or_create_by(name: "Big Black Furry Creature from Mars")
Song.find_or_create_by(name: "Big Black Furry Creature from Mars Jam")
Song.find_or_create_by(name: "Big Leg Emma")
Song.find_or_create_by(name: "Big Pimpin'")
Song.find_or_create_by(name: "Bike")
Song.find_or_create_by(name: "Bill Bailey, Won't You Please Come Home?")
Song.find_or_create_by(name: "Billie Jean Jam")
Song.find_or_create_by(name: "Billy Breathes")
Song.find_or_create_by(name: "Birds of a Feather")
Song.find_or_create_by(name: "Birthday")
Song.find_or_create_by(name: "Bitchin' Again")
Song.find_or_create_by(name: "Bittersweet Motel")
Song.find_or_create_by(name: "Black and Tan Fantasy")
Song.find_or_create_by(name: "Black-Eyed Katy")
Song.find_or_create_by(name: "Blackbird")
Song.find_or_create_by(name: "Blaze On")
Song.find_or_create_by(name: "Blister in the Sun")
Song.find_or_create_by(name: "Blister in the Sun Jam")
Song.find_or_create_by(name: "Blue Bayou")
Song.find_or_create_by(name: "Blue Bossa")
Song.find_or_create_by(name: "Blue Monk")
Song.find_or_create_by(name: "Blue Moon")
Song.find_or_create_by(name: "Blue Skies")
Song.find_or_create_by(name: "Blue Sky")
Song.find_or_create_by(name: "Bluegrass")
Song.find_or_create_by(name: "Bobby Jean")
Song.find_or_create_by(name: "Bohemian Rhapsody")
Song.find_or_create_by(name: "Bold As Love")
Song.find_or_create_by(name: "Boogie On Reggae Woman")
Song.find_or_create_by(name: "Born Under Punches (The Heat Goes On)")
Song.find_or_create_by(name: "Born to Run")
Song.find_or_create_by(name: "Bouncing Around the Room")
Song.find_or_create_by(name: "Brain Damage")
Song.find_or_create_by(name: "Breath and Burning")
Song.find_or_create_by(name: "Breathe")
Song.find_or_create_by(name: "Breathe Jam")
Song.find_or_create_by(name: "Brian and Robert")
Song.find_or_create_by(name: "Bring It On Home")
Song.find_or_create_by(name: "Brother")
Song.find_or_create_by(name: "Brown Eyed Girl")
Song.find_or_create_by(name: "Buffalo Bill")
Song.find_or_create_by(name: "Bug")
Song.find_or_create_by(name: "Bundle of Joy")
Song.find_or_create_by(name: "Buried Alive")
Song.find_or_create_by(name: "Burn That Bridge")
Song.find_or_create_by(name: "Burning Down the House")
Song.find_or_create_by(name: "Bye Bye Foot")
Song.find_or_create_by(name: "California Love Jam")
Song.find_or_create_by(name: "Call It Stormy Monday (But Tuesday Is Just As Bad)")
Song.find_or_create_by(name: "Camel Walk")
Song.find_or_create_by(name: "Can't Always Listen")
Song.find_or_create_by(name: "Can't You Hear Me Knocking")
Song.find_or_create_by(name: "Cannonball Jam")
Song.find_or_create_by(name: "Caravan")
Song.find_or_create_by(name: "Carefree")
Song.find_or_create_by(name: "Carini")
Song.find_or_create_by(name: "Carolina")
Song.find_or_create_by(name: "Cars Trucks Buses")
Song.find_or_create_by(name: "Casino Boogie")
Song.find_or_create_by(name: "Catapult")
Song.find_or_create_by(name: "Cavern")
Song.find_or_create_by(name: "Cecilia")
Song.find_or_create_by(name: "Chalk Dust Torture")
Song.find_or_create_by(name: "Chalk Dust Torture Reprise")
Song.find_or_create_by(name: "Champagne Supernova")
Song.find_or_create_by(name: "Character Zero")
Song.find_or_create_by(name: "Chariots of Fire")
Song.find_or_create_by(name: "Che Hun Ta Mo")
Song.find_or_create_by(name: "Chocolate Rain")
Song.find_or_create_by(name: "Choo Choo Ch' Boogie")
Song.find_or_create_by(name: "Cinnamon Girl")
Song.find_or_create_by(name: "Cities")
Song.find_or_create_by(name: "Clod")
Song.find_or_create_by(name: "Clone")
Song.find_or_create_by(name: "Cocaine Jam")
Song.find_or_create_by(name: "Coconut")
Song.find_or_create_by(name: "Cold Rain and Snow")
Song.find_or_create_by(name: "Cold Water")
Song.find_or_create_by(name: "Cold as Ice")
Song.find_or_create_by(name: "Colonel Forbin's Ascent")
Song.find_or_create_by(name: "Come On (Part One)")
Song.find_or_create_by(name: "Come Together (The Beatles)")
Song.find_or_create_by(name: "Come on Baby Let's Go Downtown")
Song.find_or_create_by(name: "Communication Breakdown")
Song.find_or_create_by(name: "Contact")
Song.find_or_create_by(name: "Cool It Down")
Song.find_or_create_by(name: "Cool Jerk")
Song.find_or_create_by(name: "Corinna")
Song.find_or_create_by(name: "Corona")
Song.find_or_create_by(name: "Costume Contest")
Song.find_or_create_by(name: "Cracklin' Rosie")
Song.find_or_create_by(name: "Crazy Sometimes")
Song.find_or_create_by(name: "Crimes of the Mind")
Song.find_or_create_by(name: "Crosseyed and Painless")
Song.find_or_create_by(name: "Crossroads")
Song.find_or_create_by(name: "Crowd Control")
Song.find_or_create_by(name: "Cry Baby Cry")
Song.find_or_create_by(name: "Cryin'")
Song.find_or_create_by(name: "Cut My Hair")
Song.find_or_create_by(name: "Dahlia")
Song.find_or_create_by(name: "Daniel Saw the Stone")
Song.find_or_create_by(name: "Dave's Energy Guide")
Song.find_or_create_by(name: "David Bowie")
Song.find_or_create_by(name: "Day or Night")
Song.find_or_create_by(name: "Dazed and Confused")
Song.find_or_create_by(name: "Dear Mrs. Reagan")
Song.find_or_create_by(name: "Dear Prudence")
Song.find_or_create_by(name: "-86956")
Song.find_or_create_by(name: "Dem Bones")
Song.find_or_create_by(name: "Demand")
Song.find_or_create_by(name: "Destiny Unbound")
Song.find_or_create_by(name: "Devotion To a Dream")
Song.find_or_create_by(name: "Diamond Girl")
Song.find_or_create_by(name: "Dickie Scotland")
Song.find_or_create_by(name: "Digital Delay Loop Jam")
Song.find_or_create_by(name: "Dinner and a Movie")
Song.find_or_create_by(name: "Dirt")
Song.find_or_create_by(name: "Discern")
Song.find_or_create_by(name: "Divided Sky")
Song.find_or_create_by(name: "Dixie Cannonball")
Song.find_or_create_by(name: "Dixie Chicken")
Song.find_or_create_by(name: "Doctor Jimmy")
Song.find_or_create_by(name: "Dog Faced Boy")
Song.find_or_create_by(name: "Dog Log")
Song.find_or_create_by(name: "Dogs Stole Things")
Song.find_or_create_by(name: "Doin' My Time")
Song.find_or_create_by(name: "Don't Bogart That Joint")
Song.find_or_create_by(name: "Don't Get Me Wrong")
Song.find_or_create_by(name: "Don't Pass Me By")
Song.find_or_create_by(name: "Don't Want You No More")
Song.find_or_create_by(name: "Don't You Want To Go?")
Song.find_or_create_by(name: "Donna Lee")
Song.find_or_create_by(name: "Dooley")
Song.find_or_create_by(name: "Down By the River")
Song.find_or_create_by(name: "Down with Disease")
Song.find_or_create_by(name: "Down with Disease Jam")
Song.find_or_create_by(name: "Dr. Gabel")
Song.find_or_create_by(name: "Drifting")
Song.find_or_create_by(name: "Drive-In Jam")
Song.find_or_create_by(name: "Driver")
Song.find_or_create_by(name: "Drowned")
Song.find_or_create_by(name: "Drums")
Song.find_or_create_by(name: "Dust in the Wind")
Song.find_or_create_by(name: "Earache My Eye")
Song.find_or_create_by(name: "Easy To Slip")
Song.find_or_create_by(name: "Eclipse")
Song.find_or_create_by(name: "El Paso")
Song.find_or_create_by(name: "Eliza")
Song.find_or_create_by(name: "Emotional Rescue")
Song.find_or_create_by(name: "End of Session")
Song.find_or_create_by(name: "Energy")
Song.find_or_create_by(name: "Esther")
Song.find_or_create_by(name: "Everybody's Got Something to Hide Except Me and My Monkey")
Song.find_or_create_by(name: "Everyday I Have the Blues")
Song.find_or_create_by(name: "Everything In Its Right Place")
Song.find_or_create_by(name: "Everything's Right")
Song.find_or_create_by(name: "Eyes of the World")
Song.find_or_create_by(name: "Faht")
Song.find_or_create_by(name: "Family Picture")
Song.find_or_create_by(name: "Farmhouse")
Song.find_or_create_by(name: "Fast Enough for You")
Song.find_or_create_by(name: "Fat Man in the Bathtub")
Song.find_or_create_by(name: "Feats Don't Fail Me Now")
Song.find_or_create_by(name: "Fee")
Song.find_or_create_by(name: "Feel the Heat")
Song.find_or_create_by(name: "Fikus")
Song.find_or_create_by(name: "Final Flight")
Song.find_or_create_by(name: "Fire")
Song.find_or_create_by(name: "Fire Up the Ganja")
Song.find_or_create_by(name: "Fire on the Mountain")
Song.find_or_create_by(name: "First Tube")
Song.find_or_create_by(name: "Five Years")
Song.find_or_create_by(name: "Fixin' to Die")
Song.find_or_create_by(name: "Flat Fee")
Song.find_or_create_by(name: "Flatbed Truck Jam")
Song.find_or_create_by(name: "Fluff's Travels")
Song.find_or_create_by(name: "Fluffhead")
Song.find_or_create_by(name: "Fly Famous Mockingbird")
Song.find_or_create_by(name: "Fly Like an Eagle")
Song.find_or_create_by(name: "Foam")
Song.find_or_create_by(name: "Foggy Mountain Breakdown")
Song.find_or_create_by(name: "Fooled Around and Fell in Love")
Song.find_or_create_by(name: "Foreplay/Long Time")
Song.find_or_create_by(name: "Four")
Song.find_or_create_by(name: "Four Strong Winds")
Song.find_or_create_by(name: "Frankenstein")
Song.find_or_create_by(name: "Frankie Says")
Song.find_or_create_by(name: "Free")
Song.find_or_create_by(name: "Free Bird")
Song.find_or_create_by(name: "Free Man in Paris")
Song.find_or_create_by(name: "Freeworld")
Song.find_or_create_by(name: "Friday")
Song.find_or_create_by(name: "Friends")
Song.find_or_create_by(name: "Frost")
Song.find_or_create_by(name: "Fuck Your Face")
Song.find_or_create_by(name: "Fuego")
Song.find_or_create_by(name: "Funky (Breakdown)")
Song.find_or_create_by(name: "Funky Bitch")
Song.find_or_create_by(name: "Garden Party")
Song.find_or_create_by(name: "Gaul Swerves and the Rest is Everything Else")
Song.find_or_create_by(name: "Gettin' Jiggy Wit' It")
Song.find_or_create_by(name: "Ghost")
Song.find_or_create_by(name: "Ginseng Sullivan")
Song.find_or_create_by(name: "Girls Girls Girls")
Song.find_or_create_by(name: "Glass Onion")
Song.find_or_create_by(name: "Glide")
Song.find_or_create_by(name: "Glide II")
Song.find_or_create_by(name: "Gloria")
Song.find_or_create_by(name: "Glory Days")
Song.find_or_create_by(name: "Goin' Down Slow")
Song.find_or_create_by(name: "Gold Soundz")
Song.find_or_create_by(name: "Golden Age")
Song.find_or_create_by(name: "Golden Lady")
Song.find_or_create_by(name: "Golgi Apparatus")
Song.find_or_create_by(name: "Gone")
Song.find_or_create_by(name: "Good Times Bad Times")
Song.find_or_create_by(name: "Got My Mojo Working")
Song.find_or_create_by(name: "Gotta Jibboo")
Song.find_or_create_by(name: "Green Onions")
Song.find_or_create_by(name: "Grind")
Song.find_or_create_by(name: "Guelah Papyrus")
Song.find_or_create_by(name: "Gumbo")
Song.find_or_create_by(name: "Guy Forget")
Song.find_or_create_by(name: "Guyute")
Song.find_or_create_by(name: "Gypsy Queen")
Song.find_or_create_by(name: "Ha Ha Ha")
Song.find_or_create_by(name: "Halfway to the Moon")
Song.find_or_create_by(name: "Halley's Comet")
Song.find_or_create_by(name: "Hang On to Yourself")
Song.find_or_create_by(name: "Happiness Is a Warm Gun")
Song.find_or_create_by(name: "Happy")
Song.find_or_create_by(name: "Happy Birthday to You")
Song.find_or_create_by(name: "Harpua")
Song.find_or_create_by(name: "Harry Hood")
Song.find_or_create_by(name: "Have Mercy")
Song.find_or_create_by(name: "Head Held High")
Song.find_or_create_by(name: "Heart and Soul")
Song.find_or_create_by(name: "Heartbreaker")
Song.find_or_create_by(name: "Heavy Rotation")
Song.find_or_create_by(name: "Heavy Things")
Song.find_or_create_by(name: "Hello My Baby")
Song.find_or_create_by(name: "Help Me")
Song.find_or_create_by(name: "Help on the Way")
Song.find_or_create_by(name: "Helpless")
Song.find_or_create_by(name: "Helpless Dancer")
Song.find_or_create_by(name: "Helter Skelter")
Song.find_or_create_by(name: "High-Heel Sneakers")
Song.find_or_create_by(name: "Highway to Hell")
Song.find_or_create_by(name: "Hold Whatcha Got")
Song.find_or_create_by(name: "Hold Your Head Up")
Song.find_or_create_by(name: "Hold Your Head Up Jam")
Song.find_or_create_by(name: "Hold to a Dream")
Song.find_or_create_by(name: "Home")
Song.find_or_create_by(name: "Honey Pie")
Song.find_or_create_by(name: "Honky Tonk Women")
Song.find_or_create_by(name: "Honky Tonk Women Jam")
Song.find_or_create_by(name: "Hoochie Coochie Man")
Song.find_or_create_by(name: "Horn")
Song.find_or_create_by(name: "Houses in Motion")
Song.find_or_create_by(name: "How High the Moon")
Song.find_or_create_by(name: "How Many People Are You")
Song.find_or_create_by(name: "Hurricane")
Song.find_or_create_by(name: "I Always Wanted It This Way")
Song.find_or_create_by(name: "I Am Hydrogen")
Song.find_or_create_by(name: "I Am the Sea")
Song.find_or_create_by(name: "I Am the Walrus")
Song.find_or_create_by(name: "I Been Around")
Song.find_or_create_by(name: "I Been to Georgia on a Fast Train")
Song.find_or_create_by(name: "I Didn't Know")
Song.find_or_create_by(name: "I Don't Care")
Song.find_or_create_by(name: "I Found a Reason")
Song.find_or_create_by(name: "I Get a Kick Out of You")
Song.find_or_create_by(name: "I Just Want To See His Face")
Song.find_or_create_by(name: "I Kissed a Girl")
Song.find_or_create_by(name: "I Know a Little")
Song.find_or_create_by(name: "I Shall Be Released")
Song.find_or_create_by(name: "I Told You So")
Song.find_or_create_by(name: "I Walk the Line")
Song.find_or_create_by(name: "I Wan'na Be Like You")
Song.find_or_create_by(name: "I Want To Be a Cowboy's Sweetheart")
Song.find_or_create_by(name: "I Will")
Song.find_or_create_by(name: "I Wish")
Song.find_or_create_by(name: "I'll Come Running")
Song.find_or_create_by(name: "I'm Blue, I'm Lonesome")
Song.find_or_create_by(name: "I'm Gonna Be (500 Miles)")
Song.find_or_create_by(name: "I'm One")
Song.find_or_create_by(name: "I'm So Tired")
Song.find_or_create_by(name: "I've Had Enough")
Song.find_or_create_by(name: "I've Turned Bad")
Song.find_or_create_by(name: "Icculus")
Song.find_or_create_by(name: "Idea")
Song.find_or_create_by(name: "If I Could")
Song.find_or_create_by(name: "If I Don't Be There By Morning")
Song.find_or_create_by(name: "If I Only Had a Brain")
Song.find_or_create_by(name: "If You Need a Fool")
Song.find_or_create_by(name: "Immigrant Song")
Song.find_or_create_by(name: "Immigrant Song Jam")
Song.find_or_create_by(name: "In The Good Old Summer Time")
Song.find_or_create_by(name: "In a Hole")
Song.find_or_create_by(name: "In a Mellow Tone")
Song.find_or_create_by(name: "In the Aeroplane Over the Sea")
Song.find_or_create_by(name: "In the Midnight Hour")
Song.find_or_create_by(name: "Instant Karma!")
Song.find_or_create_by(name: "Intro")
Song.find_or_create_by(name: "Invisible")
Song.find_or_create_by(name: "Iron Man")
Song.find_or_create_by(name: "Is It In My Head?")
Song.find_or_create_by(name: "Is This What You Wanted")
Song.find_or_create_by(name: "It Ain't Easy")
Song.find_or_create_by(name: "It's All Right")
Song.find_or_create_by(name: "It's Ice")
Song.find_or_create_by(name: "Izabella")
Song.find_or_create_by(name: "Jam")
Song.find_or_create_by(name: "Jennifer Dances")
Song.find_or_create_by(name: "Jessica Jam")
Song.find_or_create_by(name: "Jesus Just Left Chicago")
Song.find_or_create_by(name: "Johnny B. Goode")
Song.find_or_create_by(name: "Joy")
Song.find_or_create_by(name: "Julia")
Song.find_or_create_by(name: "Julius")
Song.find_or_create_by(name: "Jump Monk")
Song.find_or_create_by(name: "Jumpin' Jack Flash")
Song.find_or_create_by(name: "Jungle Boogie")
Song.find_or_create_by(name: "JÃ¤germeister Song")
Song.find_or_create_by(name: "Keyboard Army")
Song.find_or_create_by(name: "Kill Devil Falls")
Song.find_or_create_by(name: "Killer Joe")
Song.find_or_create_by(name: "Killing in the Name")
Song.find_or_create_by(name: "Kung")
Song.find_or_create_by(name: "L.A. Woman")
Song.find_or_create_by(name: "La Grange")
Song.find_or_create_by(name: "La Grange Jam")
Song.find_or_create_by(name: "Lady Stardust")
Song.find_or_create_by(name: "Lawn Boy")
Song.find_or_create_by(name: "Lawn Boy Reprise")
Song.find_or_create_by(name: "Layla")
Song.find_or_create_by(name: "Le Freak")
Song.find_or_create_by(name: "Leaves")
Song.find_or_create_by(name: "Legalize It")
Song.find_or_create_by(name: "Lengthwise")
Song.find_or_create_by(name: "Leprechaun")
Song.find_or_create_by(name: "Let It Loose")
Song.find_or_create_by(name: "Let Me Lie")
Song.find_or_create_by(name: "Let's Go")
Song.find_or_create_by(name: "Let's Go (The Cars)")
Song.find_or_create_by(name: "Letter to Jimmy Page")
Song.find_or_create_by(name: "Life on Mars?")
Song.find_or_create_by(name: "Lifeboy")
Song.find_or_create_by(name: "Light")
Song.find_or_create_by(name: "Light Up Or Leave Me Alone")
Song.find_or_create_by(name: "Limb By Limb")
Song.find_or_create_by(name: "Listening Wind")
Song.find_or_create_by(name: "Lit O Bit")
Song.find_or_create_by(name: "Little Red Rooster")
Song.find_or_create_by(name: "Little Tiny Butter Biscuits")
Song.find_or_create_by(name: "Lively Up Yourself")
Song.find_or_create_by(name: "Llama")
Song.find_or_create_by(name: "Lonesome Cowboy Bill")
Song.find_or_create_by(name: "Long Cool Woman in a Black Dress")
Song.find_or_create_by(name: "Long Long Long")
Song.find_or_create_by(name: "Look Out Cleveland")
Song.find_or_create_by(name: "Loup Garou")
Song.find_or_create_by(name: "Love Is What We Are")
Song.find_or_create_by(name: "Love Me")
Song.find_or_create_by(name: "Love Me Like a Man")
Song.find_or_create_by(name: "Love You")
Song.find_or_create_by(name: "Love, Reign O'er Me")
Song.find_or_create_by(name: "Loving Cup")
Song.find_or_create_by(name: "Low Rider")
Song.find_or_create_by(name: "Low Rider Jam")
Song.find_or_create_by(name: "Lucky Seven")
Song.find_or_create_by(name: "Lullaby of Birdland")
Song.find_or_create_by(name: "Lushington")
Song.find_or_create_by(name: "Magilla")
Song.find_or_create_by(name: "Maiden Voyage")
Song.find_or_create_by(name: "Makisupa Policeman")
Song.find_or_create_by(name: "Makisupa Policeman Jam")
Song.find_or_create_by(name: "Mallory")
Song.find_or_create_by(name: "Manteca")
Song.find_or_create_by(name: "Maple Leaf Rag")
Song.find_or_create_by(name: "Marissa")
Song.find_or_create_by(name: "Martha My Dear")
Song.find_or_create_by(name: "Martian Monster")
Song.find_or_create_by(name: "Maze")
Song.find_or_create_by(name: "McGrupp and the Watchful Hosemasters")
Song.find_or_create_by(name: "Mean Mr. Mustard")
Song.find_or_create_by(name: "Meat")
Song.find_or_create_by(name: "Meatstick")
Song.find_or_create_by(name: "Mellow Mood")
Song.find_or_create_by(name: "Melt the Guns")
Song.find_or_create_by(name: "Memories")
Song.find_or_create_by(name: "Mercenary Territory")
Song.find_or_create_by(name: "Mercury")
Song.find_or_create_by(name: "Merry Pranksters Jam")
Song.find_or_create_by(name: "Messin' with The Kid")
Song.find_or_create_by(name: "Metal Bagel Death")
Song.find_or_create_by(name: "Mexican Cousin")
Song.find_or_create_by(name: "Middle of the Road")
Song.find_or_create_by(name: "Midnight Rider Jam")
Song.find_or_create_by(name: "Midnight on the Highway")
Song.find_or_create_by(name: "Mike's Song")
Song.find_or_create_by(name: "Mind Left Body Jam")
Song.find_or_create_by(name: "Minute by Minute")
Song.find_or_create_by(name: "Mirror in the Bathroom")
Song.find_or_create_by(name: "Miss You")
Song.find_or_create_by(name: "Misty Mountain Hop")
Song.find_or_create_by(name: "Mo' Better Blues")
Song.find_or_create_by(name: "Moby Dick")
Song.find_or_create_by(name: "Mock Song")
Song.find_or_create_by(name: "Money")
Song.find_or_create_by(name: "Monkey Man")
Song.find_or_create_by(name: "Moonage Daydream")
Song.find_or_create_by(name: "Moonlight in Vermont")
Song.find_or_create_by(name: "Moose the Mooche")
Song.find_or_create_by(name: "More")
Song.find_or_create_by(name: "Most Events Aren't Planned")
Song.find_or_create_by(name: "Mother Nature's Son")
Song.find_or_create_by(name: "Mound")
Song.find_or_create_by(name: "Mountains in the Mist")
Song.find_or_create_by(name: "Mozambique")
Song.find_or_create_by(name: "Mr. Completely")
Song.find_or_create_by(name: "Mr. P.C.")
Song.find_or_create_by(name: "Mustang Sally")
Song.find_or_create_by(name: "My Favorite Things")
Song.find_or_create_by(name: "My Friend, My Friend")
Song.find_or_create_by(name: "My Generation")
Song.find_or_create_by(name: "My Left Toe")
Song.find_or_create_by(name: "My Life As a Pez")
Song.find_or_create_by(name: "My Long Journey Home")
Song.find_or_create_by(name: "My Mind's Got a Mind of its Own")
Song.find_or_create_by(name: "My Problem Right There")
Song.find_or_create_by(name: "My Soul")
Song.find_or_create_by(name: "My Sweet One")
Song.find_or_create_by(name: "NICU")
Song.find_or_create_by(name: "NO2")
Song.find_or_create_by(name: "Nellie Kane")
Song.find_or_create_by(name: "Never")
Song.find_or_create_by(name: "New Age")
Song.find_or_create_by(name: "New York, New York")
Song.find_or_create_by(name: "Night Moves Jam")
Song.find_or_create_by(name: "Night Nurse")
Song.find_or_create_by(name: "Night and Day")
Song.find_or_create_by(name: "Ninety-Nine Years (and One Dark Day)")
Song.find_or_create_by(name: "No Dogs Allowed")
Song.find_or_create_by(name: "No Good Trying")
Song.find_or_create_by(name: "No Men In No Man's Land")
Song.find_or_create_by(name: "No Quarter")
Song.find_or_create_by(name: "Not Fade Away")
Song.find_or_create_by(name: "Nothin' But A Nothin'")
Song.find_or_create_by(name: "Nothing")
Song.find_or_create_by(name: "Nowhere Fast")
Song.find_or_create_by(name: "O Canada")
Song.find_or_create_by(name: "O Holy Night")
Song.find_or_create_by(name: "O Mio Babbino Caro")
Song.find_or_create_by(name: "Ob-La-Di, Ob-La-Da")
Song.find_or_create_by(name: "Ob-La-Di, Ob-La-Da Jam")
Song.find_or_create_by(name: "Ocelot")
Song.find_or_create_by(name: "Oh Atlanta")
Song.find_or_create_by(name: "Oh! Sweet Nuthin'")
Song.find_or_create_by(name: "Old Folks Boogie")
Song.find_or_create_by(name: "Olivia's Pool")
Song.find_or_create_by(name: "On Green Dolphin Street")
Song.find_or_create_by(name: "On My Knees")
Song.find_or_create_by(name: "On The Run")
Song.find_or_create_by(name: "On Your Way Down")
Song.find_or_create_by(name: "On the Road Again")
Song.find_or_create_by(name: "Once in a Lifetime")
Song.find_or_create_by(name: "One Meatball")
Song.find_or_create_by(name: "Oye Como Va Jam")
Song.find_or_create_by(name: "P-Funk Medley")
Song.find_or_create_by(name: "Party Time")
Song.find_or_create_by(name: "Paul and Silas")
Song.find_or_create_by(name: "Peaches en Regalia")
Song.find_or_create_by(name: "Pebbles and Marbles")
Song.find_or_create_by(name: "Petrichor")
Song.find_or_create_by(name: "Phase Dance")
Song.find_or_create_by(name: "Piano Duet")
Song.find_or_create_by(name: "Pig in a Pen")
Song.find_or_create_by(name: "Piggies")
Song.find_or_create_by(name: "Pigtail")
Song.find_or_create_by(name: "Piper")
Song.find_or_create_by(name: "Plasma")
Song.find_or_create_by(name: "Playing in the Band")
Song.find_or_create_by(name: "Poor Heart")
Song.find_or_create_by(name: "Possum")
Song.find_or_create_by(name: "Powderfinger")
Song.find_or_create_by(name: "Prep School Hippie")
Song.find_or_create_by(name: "Prince Caspian")
Song.find_or_create_by(name: "Proud Mary")
Song.find_or_create_by(name: "Psycho Killer")
Song.find_or_create_by(name: "Punch Me in the Eye")
Song.find_or_create_by(name: "Punch You In the Eye")
Song.find_or_create_by(name: "Purple Rain")
Song.find_or_create_by(name: "Pusherman Jam")
Song.find_or_create_by(name: "Quadrophenia")
Song.find_or_create_by(name: "Quadrophonic Toppling")
Song.find_or_create_by(name: "Quinn the Eskimo")
Song.find_or_create_by(name: "Ramble On")
Song.find_or_create_by(name: "Rapper's Delight")
Song.find_or_create_by(name: "Reba")
Song.find_or_create_by(name: "Revival")
Song.find_or_create_by(name: "Revolution")
Song.find_or_create_by(name: "Revolution 1")
Song.find_or_create_by(name: "Revolution 9")
Song.find_or_create_by(name: "Revolution's Over")
Song.find_or_create_by(name: "Rhinoceros")
Song.find_or_create_by(name: "Rhombus Narration")
Song.find_or_create_by(name: "Rhymes")
Song.find_or_create_by(name: "Ride Captain Ride")
Song.find_or_create_by(name: "Rift")
Song.find_or_create_by(name: "Rip This Joint")
Song.find_or_create_by(name: "Rise/Come Together")
Song.find_or_create_by(name: "Roadhouse Blues")
Song.find_or_create_by(name: "Roadrunner")
Song.find_or_create_by(name: "Rock 'n' Roll Suicide")
Song.find_or_create_by(name: "Rock A William")
Song.find_or_create_by(name: "Rock Me Baby")
Song.find_or_create_by(name: "Rock and Roll")
Song.find_or_create_by(name: "Rock and Roll All Nite Jam")
Song.find_or_create_by(name: "Rock and Roll Part Two")
Song.find_or_create_by(name: "Rocket Man")
Song.find_or_create_by(name: "Rocket in My Pocket")
Song.find_or_create_by(name: "Rocks Off")
Song.find_or_create_by(name: "Rocky Mountain Way Jam")
Song.find_or_create_by(name: "Rocky Raccoon")
Song.find_or_create_by(name: "Rocky Top")
Song.find_or_create_by(name: "Roggae")
Song.find_or_create_by(name: "Roll Like a Cantaloupe")
Song.find_or_create_by(name: "Roll in My Sweet Baby's Arms")
Song.find_or_create_by(name: "Roses Are Free")
Song.find_or_create_by(name: "Rotation Jam")
Song.find_or_create_by(name: "Round Room")
Song.find_or_create_by(name: "Run Like an Antelope")
Song.find_or_create_by(name: "Runaway Jim")
Song.find_or_create_by(name: "Runnin' with the Devil")
Song.find_or_create_by(name: "Running Out of Time")
Song.find_or_create_by(name: "Sabotage")
Song.find_or_create_by(name: "Sad Lisa")
Song.find_or_create_by(name: "Sailin' Shoes")
Song.find_or_create_by(name: "Sample in a Jar")
Song.find_or_create_by(name: "Samson Variation")
Song.find_or_create_by(name: "Samson and Delilah")
Song.find_or_create_by(name: "Sand")
Song.find_or_create_by(name: "Sanity")
Song.find_or_create_by(name: "Satin Doll")
Song.find_or_create_by(name: "Savoy Truffle")
Song.find_or_create_by(name: "Saw It Again")
Song.find_or_create_by(name: "Say Something")
Song.find_or_create_by(name: "Scabbard")
Song.find_or_create_by(name: "Scarlet Begonias")
Song.find_or_create_by(name: "Scent of a Mule")
Song.find_or_create_by(name: "Scents and Subtle Sounds")
Song.find_or_create_by(name: "Sea and Sand")
Song.find_or_create_by(name: "Secret Language Instructions")
Song.find_or_create_by(name: "Secret Smile")
Song.find_or_create_by(name: "See That My Grave Is Kept Clean")
Song.find_or_create_by(name: "Seen and Not Seen")
Song.find_or_create_by(name: "Self")
Song.find_or_create_by(name: "Setting Sail")
Song.find_or_create_by(name: "Seven Below")
Song.find_or_create_by(name: "Sexual Healing")
Song.find_or_create_by(name: "Sexy Sadie")
Song.find_or_create_by(name: "Shade")
Song.find_or_create_by(name: "Shafty")
Song.find_or_create_by(name: "Shaggy Dog")
Song.find_or_create_by(name: "Shake Your Coconuts")
Song.find_or_create_by(name: "Shake Your Hips")
Song.find_or_create_by(name: "She Caught the Katy and Left Me a Mule to Ride")
Song.find_or_create_by(name: "She Thinks I Still Care")
Song.find_or_create_by(name: "Shine")
Song.find_or_create_by(name: "Shine a Light")
Song.find_or_create_by(name: "Shipwreck")
Song.find_or_create_by(name: "Show of Life")
Song.find_or_create_by(name: "Silent in the Morning")
Song.find_or_create_by(name: "Simple")
Song.find_or_create_by(name: "Sing Monica")
Song.find_or_create_by(name: "Sixteen Candles")
Song.find_or_create_by(name: "Skin It Back")
Song.find_or_create_by(name: "Skippy the Wondermouse")
Song.find_or_create_by(name: "Slave to the Traffic Light")
Song.find_or_create_by(name: "Sleep")
Song.find_or_create_by(name: "Sleep Again")
Song.find_or_create_by(name: "Sleeping Monkey")
Song.find_or_create_by(name: "Slipknot!")
Song.find_or_create_by(name: "Smells Like Teen Spirit")
Song.find_or_create_by(name: "Smoke on the Water Jam")
Song.find_or_create_by(name: "Sneakin' Sally Through the Alley")
Song.find_or_create_by(name: "Snow")
Song.find_or_create_by(name: "So Lonely")
Song.find_or_create_by(name: "Something")
Song.find_or_create_by(name: "Somewhere Over the Rainbow")
Song.find_or_create_by(name: "Soul Love")
Song.find_or_create_by(name: "Soul Planet")
Song.find_or_create_by(name: "Soul Shakedown Party")
Song.find_or_create_by(name: "Soul Survivor")
Song.find_or_create_by(name: "Space Oddity")
Song.find_or_create_by(name: "Spanish Flea")
Song.find_or_create_by(name: "Spanish Moon")
Song.find_or_create_by(name: "Sparkle")
Song.find_or_create_by(name: "Sparks")
Song.find_or_create_by(name: "Speak to Me")
Song.find_or_create_by(name: "Spices")
Song.find_or_create_by(name: "Split Open and Melt")
Song.find_or_create_by(name: "Split Open and Melt Jam")
Song.find_or_create_by(name: "Spock's Brain")
Song.find_or_create_by(name: "Spooky")
Song.find_or_create_by(name: "Spooky Jam")
Song.find_or_create_by(name: "Spread It 'Round")
Song.find_or_create_by(name: "Squeeze Box")
Song.find_or_create_by(name: "St. Stephen Jam")
Song.find_or_create_by(name: "St. Thomas")
Song.find_or_create_by(name: "Stairway to Heaven")
Song.find_or_create_by(name: "Stand!")
Song.find_or_create_by(name: "Star")
Song.find_or_create_by(name: "Starman")
Song.find_or_create_by(name: "Stash")
Song.find_or_create_by(name: "Stealing Time From the Faulty Plan")
Song.find_or_create_by(name: "Steam")
Song.find_or_create_by(name: "Steep")
Song.find_or_create_by(name: "Stir It Up Jam")
Song.find_or_create_by(name: "Stop Breaking Down")
Song.find_or_create_by(name: "Storage Jam")
Song.find_or_create_by(name: "Strange Design")
Song.find_or_create_by(name: "Strawberry Fields Forever")
Song.find_or_create_by(name: "Strawberry Letter 23")
Song.find_or_create_by(name: "Suffragette City")
Song.find_or_create_by(name: "Sugar Shack")
Song.find_or_create_by(name: "Summer of '89")
Song.find_or_create_by(name: "Sunday Morning")
Song.find_or_create_by(name: "Sunshine of Your Feeling")
Song.find_or_create_by(name: "Suspicious Minds")
Song.find_or_create_by(name: "Susskind Hotel")
Song.find_or_create_by(name: "Suzy Greenberg")
Song.find_or_create_by(name: "Sweet Adeline")
Song.find_or_create_by(name: "Sweet Black Angel")
Song.find_or_create_by(name: "Sweet Emotion Jam")
Song.find_or_create_by(name: "Sweet Georgia Brown")
Song.find_or_create_by(name: "Sweet Jane")
Song.find_or_create_by(name: "Sweet Virginia")
Song.find_or_create_by(name: "Swept Away")
Song.find_or_create_by(name: "Swing Low, Sweet Chariot")
Song.find_or_create_by(name: "Sympathy for the Devil")
Song.find_or_create_by(name: "T.V. Show")
Song.find_or_create_by(name: "T.V. Theme")
Song.find_or_create_by(name: "Take Me Out to the Ballgame")
Song.find_or_create_by(name: "Take Me to the River")
Song.find_or_create_by(name: "Take the 'A' Train")
Song.find_or_create_by(name: "Takin' Care of Business")
Song.find_or_create_by(name: "Talk")
Song.find_or_create_by(name: "Taste")
Song.find_or_create_by(name: "Taste That Surrounds")
Song.find_or_create_by(name: "Tela")
Song.find_or_create_by(name: "Tell Me Something Good")
Song.find_or_create_by(name: "Tennessee Waltz")
Song.find_or_create_by(name: "Terrapin")
Song.find_or_create_by(name: "Terrapin Station")
Song.find_or_create_by(name: "Thank You")
Song.find_or_create_by(name: "That's Alright Mama")
Song.find_or_create_by(name: "The Asse Festival")
Song.find_or_create_by(name: "The Ballad of Curtis Loew")
Song.find_or_create_by(name: "The Birds")
Song.find_or_create_by(name: "The Birdwatcher")
Song.find_or_create_by(name: "The Chase")
Song.find_or_create_by(name: "The Chicken")
Song.find_or_create_by(name: "The Chinese Water Torture")
Song.find_or_create_by(name: "The Connection")
Song.find_or_create_by(name: "The Continuing Story of Bungalow Bill")
Song.find_or_create_by(name: "The Cover of 'Rolling Stone'")
Song.find_or_create_by(name: "The Curtain")
Song.find_or_create_by(name: "The Curtain With")
Song.find_or_create_by(name: "The Dirty Jobs")
Song.find_or_create_by(name: "The Dogs")
Song.find_or_create_by(name: "The Fishin' Hole")
Song.find_or_create_by(name: "The Fog That Surrounds")
Song.find_or_create_by(name: "The Gambler")
Song.find_or_create_by(name: "The Great Curve")
Song.find_or_create_by(name: "The Great Gig in the Sky")
Song.find_or_create_by(name: "The Happy Whip and Dung Song")
Song.find_or_create_by(name: "The Haunted House")
Song.find_or_create_by(name: "The Horse")
Song.find_or_create_by(name: "The Inlaw Josie Wales")
Song.find_or_create_by(name: "The Landlady")
Song.find_or_create_by(name: "The Last Step")
Song.find_or_create_by(name: "The Line")
Song.find_or_create_by(name: "The Lion Sleeps Tonight")
Song.find_or_create_by(name: "The Little Drummer Boy")
Song.find_or_create_by(name: "The Lizards")
Song.find_or_create_by(name: "The Maker")
Song.find_or_create_by(name: "The Man Who Stepped Into Yesterday")
Song.find_or_create_by(name: "The Mango Song")
Song.find_or_create_by(name: "The Moma Dance")
Song.find_or_create_by(name: "The Ocean")
Song.find_or_create_by(name: "The Oh Kee Pa Ceremony")
Song.find_or_create_by(name: "The Old Home Place")
Song.find_or_create_by(name: "The Other One")
Song.find_or_create_by(name: "The Overload")
Song.find_or_create_by(name: "The Pendulum")
Song.find_or_create_by(name: "The Practical Song")
Song.find_or_create_by(name: "The Price of Love")
Song.find_or_create_by(name: "The Prison Joke")
Song.find_or_create_by(name: "The Punk Meets the Godfather")
Song.find_or_create_by(name: "The Real Me")
Song.find_or_create_by(name: "The Rock")
Song.find_or_create_by(name: "The Rover")
Song.find_or_create_by(name: "The Sloth")
Song.find_or_create_by(name: "The Squirming Coil")
Song.find_or_create_by(name: "The Star Spangled Banner")
Song.find_or_create_by(name: "The Tears of a Clown")
Song.find_or_create_by(name: "The Thrill is Gone")
Song.find_or_create_by(name: "The Unsafe Bridge")
Song.find_or_create_by(name: "The Very Long Fuse")
Song.find_or_create_by(name: "The Vibration of Life")
Song.find_or_create_by(name: "The Way It Goes")
Song.find_or_create_by(name: "The Wedge")
Song.find_or_create_by(name: "The Wind Cries Mary")
Song.find_or_create_by(name: "Them Changes")
Song.find_or_create_by(name: "Theme From the Bottom")
Song.find_or_create_by(name: "Theme from Star Trek")
Song.find_or_create_by(name: "Things People Do")
Song.find_or_create_by(name: "Thread")
Song.find_or_create_by(name: "Three Little Birds")
Song.find_or_create_by(name: "Thunder Road")
Song.find_or_create_by(name: "Thunderhead")
Song.find_or_create_by(name: "Tide Turns")
Song.find_or_create_by(name: "Timber")
Song.find_or_create_by(name: "Timber Ho!")
Song.find_or_create_by(name: "Time")
Song.find_or_create_by(name: "Time Loves a Hero")
Song.find_or_create_by(name: "Time Turns Elastic")
Song.find_or_create_by(name: "To France")
Song.find_or_create_by(name: "Tomorrow's Song")
Song.find_or_create_by(name: "Tonight")
Song.find_or_create_by(name: "Torn and Frayed")
Song.find_or_create_by(name: "Touch Me")
Song.find_or_create_by(name: "Tower Jam")
Song.find_or_create_by(name: "Train Round the Bend")
Song.find_or_create_by(name: "Train Song")
Song.find_or_create_by(name: "Trench Town Rock")
Song.find_or_create_by(name: "Tripe Face Boogie")
Song.find_or_create_by(name: "Tube")
Song.find_or_create_by(name: "Tubthumping")
Song.find_or_create_by(name: "Tuesday")
Song.find_or_create_by(name: "Tuesday's Gone")
Song.find_or_create_by(name: "Tumbling Dice")
Song.find_or_create_by(name: "Turd on the Run")
Song.find_or_create_by(name: "Tush")
Song.find_or_create_by(name: "Tweezer")
Song.find_or_create_by(name: "Tweezer Reprise")
Song.find_or_create_by(name: "Tweezer Reprise Jam")
Song.find_or_create_by(name: "Twenty Years Later")
Song.find_or_create_by(name: "Twist")
Song.find_or_create_by(name: "Two Versions of Me")
Song.find_or_create_by(name: "Uncle Pen")
Song.find_or_create_by(name: "Uncloudy Day")
Song.find_or_create_by(name: "Undermind")
Song.find_or_create_by(name: "Undun")
Song.find_or_create_by(name: "United We Stand")
Song.find_or_create_by(name: "Us and Them")
Song.find_or_create_by(name: "Vacuum Solo")
Song.find_or_create_by(name: "Ventilator Blues")
Song.find_or_create_by(name: "Viola Lee Blues")
Song.find_or_create_by(name: "Vultures")
Song.find_or_create_by(name: "Wading in the Velvet Sea")
Song.find_or_create_by(name: "Wait")
Song.find_or_create_by(name: "Waiting All Night")
Song.find_or_create_by(name: "Waking Up")
Song.find_or_create_by(name: "Waking Up Dead")
Song.find_or_create_by(name: "Walfredo")
Song.find_or_create_by(name: "Walk Away")
Song.find_or_create_by(name: "Walk This Way")
Song.find_or_create_by(name: "Walls of the Cave")
Song.find_or_create_by(name: "Waste")
Song.find_or_create_by(name: "Water in the Sky")
Song.find_or_create_by(name: "Waves")
Song.find_or_create_by(name: "Way Down in the Hole")
Song.find_or_create_by(name: "We're Not Gonna Take It")
Song.find_or_create_by(name: "We're an American Band")
Song.find_or_create_by(name: "Weekapaug Groove")
Song.find_or_create_by(name: "Weigh")
Song.find_or_create_by(name: "West L.A. Fadeaway")
Song.find_or_create_by(name: "What Things Seem")
Song.find_or_create_by(name: "What's the Use?")
Song.find_or_create_by(name: "When Something is Wrong with My Baby")
Song.find_or_create_by(name: "When the Cactus is in Bloom")
Song.find_or_create_by(name: "When the Circus Comes")
Song.find_or_create_by(name: "While My Guitar Gently Weeps")
Song.find_or_create_by(name: "Whipping Post")
Song.find_or_create_by(name: "Whipping Post Jam")
Song.find_or_create_by(name: "White Rabbit Jam")
Song.find_or_create_by(name: "White Winter Hymnal")
Song.find_or_create_by(name: "Who By Fire")
Song.find_or_create_by(name: "Who Do? We Do!")
Song.find_or_create_by(name: "Who Knows Jam")
Song.find_or_create_by(name: "Who Loves the Sun?")
Song.find_or_create_by(name: "Whole Lotta Love")
Song.find_or_create_by(name: "Whole Lotta Love Jam")
Song.find_or_create_by(name: "Why Don't We Do It in the Road?")
Song.find_or_create_by(name: "Why Don't You Love Me?")
Song.find_or_create_by(name: "Why You Been Gone So Long?")
Song.find_or_create_by(name: "Wild Child")
Song.find_or_create_by(name: "Wild Honey Pie")
Song.find_or_create_by(name: "Wild Thing")
Song.find_or_create_by(name: "Wildwood Weed")
Song.find_or_create_by(name: "Will It Go Round in Circles?")
Song.find_or_create_by(name: "Will the Circle Be Unbroken?")
Song.find_or_create_by(name: "Willin'")
Song.find_or_create_by(name: "Wilson")
Song.find_or_create_by(name: "Wind Beneath My Wings")
Song.find_or_create_by(name: "Windora Bug")
Song.find_or_create_by(name: "Windy City")
Song.find_or_create_by(name: "Wingsuit")
Song.find_or_create_by(name: "Winterqueen")
Song.find_or_create_by(name: "Wipe Out")
Song.find_or_create_by(name: "Wolfman's Brother")
Song.find_or_create_by(name: "Wombat")
Song.find_or_create_by(name: "Woodstock")
Song.find_or_create_by(name: "Wormtown Jam")
Song.find_or_create_by(name: "Ya Mar")
Song.find_or_create_by(name: "Yarmouth Road")
Song.find_or_create_by(name: "Yer Blues")
Song.find_or_create_by(name: "Yerushalayim Shel Zahav")
Song.find_or_create_by(name: "You Ain't Goin' Nowhere")
Song.find_or_create_by(name: "You Better Believe It Baby")
Song.find_or_create_by(name: "You Enjoy Myself")
Song.find_or_create_by(name: "You Gotta See Mama Every Night")
Song.find_or_create_by(name: "You Never Know")
Song.find_or_create_by(name: "You Sexy Thing")
Song.find_or_create_by(name: "You Shook Me All Night Long")
Song.find_or_create_by(name: "You Shook Me All Night Long Jam")
Song.find_or_create_by(name: "Your Pet Cat")
Song.find_or_create_by(name: "Ziggy Stardust")
